# Generated by Django 2.1.2 on 2019-02-22 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, db_index=True, default='', help_text='Subject for identity token', max_length=64)),
                ('nickname', models.CharField(blank=True, default='', help_text='Nickname, alias, or other names used.', max_length=255)),
                ('email_verified', models.BooleanField(blank=True, default=False)),
                ('phone_verified', models.BooleanField(blank=True, default=False)),
                ('mobile_phone_number', models.CharField(blank=True, default='', help_text='US numbers only.', max_length=25)),
                ('mobile_phone_number_verified', models.BooleanField(blank=True, default=False)),
                ('four_digit_suffix', models.CharField(blank=True, default='', help_text='If populated, this field must contain exactly four numbers.', max_length=4)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], default='U', help_text='Sex', max_length=1)),
                ('gender_identity', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('TMF', 'Transgender Male to Female'), ('TFM', 'Transgender Female to Male'), ('U', 'Unknown')], default='U', help_text='Gender / Gender Identity', max_length=3)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('most_recent_id_token_payload', models.TextField(blank=True, default='', max_length=4096)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
