# Generated by Django 2.1.2 on 2019-03-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190320_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='identity_assurance_level',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='1', help_text='Identity Assurance Level', max_length=1),
        ),
    ]
