# Generated by Django 2.1.2 on 2019-03-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_identity_assurance_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='picture_url',
            field=models.CharField(blank=True, default='', help_text='A public URL to a profile picture', max_length=1024),
        ),
    ]
