# Generated by Django 2.1.2 on 2019-03-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_picture_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('', 'Unknown')], default='', help_text='Birth Sex Gender', max_length=6),
        ),
    ]
