# Generated by Django 2.1.1 on 2018-09-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_userprofile_authorize_applications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='loa',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='aal',
            field=models.CharField(choices=[('1', 'ALA-1'), ('2', 'AAL-2'), ('3', 'AAL-3')], default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ial',
            field=models.CharField(choices=[('1', 'ILA-1'), ('2', 'IAL-2'), ('3', 'IAL-3')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='access_key_reset',
            field=models.BooleanField(blank=True, default=False, help_text='Check this box to issue a new access key. Doing so invalidates the existing key.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='authorize_applications',
            field=models.BooleanField(blank=True, default=False, help_text='Check this to allow the account to authorize applications.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='create_applications',
            field=models.BooleanField(blank=True, default=False, help_text='Check this to allow the account to register applications.'),
        ),
        migrations.AlterField(
            model_name='userregistercode',
            name='resend',
            field=models.BooleanField(default=False, help_text='Check to resend'),
        ),
    ]
