# Generated by Django 2.1.2 on 2019-02-19 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crosswalk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fhir_source', models.CharField(blank=True, default='http://fhir-test.sharemy.health:8080/fhir/baseDstu3/', max_length=512)),
                ('fhir_patient_id', models.CharField(blank=True, default='', max_length=80)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_identifier', models.CharField(default='', max_length=120)),
                ('user_id_type', models.CharField(choices=[('CIN', 'CIN')], default='CIN', max_length=1)),
                ('user_id_hash', models.CharField(blank=True, default='', max_length=64, verbose_name='PBKDF2 of User ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='crosswalk',
            unique_together={('user', 'user_identifier', 'user_id_type')},
        ),
    ]
