# Generated by Django 2.1.2 on 2019-02-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhirproxy', '0002_auto_20190221_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crosswalk',
            name='user_id_type',
            field=models.CharField(blank=True, choices=[('CIN', 'CIN')], default='CIN', max_length=3),
        ),
        migrations.AlterField(
            model_name='crosswalk',
            name='user_identifier',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
