# Generated by Django 2.1.2 on 2019-04-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hixny', '0002_auto_20190405_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='hixnyprofile',
            name='user_accept',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
