# Generated by Django 2.1.2 on 2019-04-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hixny', '0003_hixnyprofile_user_accept'),
    ]

    operations = [
        migrations.AddField(
            model_name='hixnyprofile',
            name='cda_content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
