# Generated by Django 2.1.2 on 2019-04-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hixny', '0004_hixnyprofile_cda_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='hixnyprofile',
            name='data_requestor',
            field=models.CharField(blank=True, default='ActualCBOUser', max_length=64),
        ),
    ]
