# Generated by Django 2.1.2 on 2019-04-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hixny', '0005_hixnyprofile_data_requestor'),
    ]

    operations = [
        migrations.AddField(
            model_name='hixnyprofile',
            name='terms_string',
            field=models.TextField(blank=True, default=''),
        ),
    ]
