
version: '3'

services:
  db:
    image: postgres
    environment:
            - POSTGRES_DB=smh
            - POSTGRES_PASSWORD=toor
    ports:
            - "5432:5432"
  smh:
    build:
            context: ../
            dockerfile: .development/Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8001
    environment:
            - DATABASES_CUSTOM=postgres://postgres:toor@db:5432/smh
            - OAUTHLIB_INSECURE_TRANSPORT=true
            - OIDC_ISSUER=http://localhost:8000
            - ALLOWED_HOSTS=web,verifymyidentity,localhost

    volumes:
      - ../:/code
    ports:
      - "8001:8001"
    depends_on:
      - db

